---
- name: install lamp stack on Centos and Ubuntu
  become: yes
  hosts: all
  tasks:
    - name: install apache
      package:
        name: httpd
        state: present
      when: ansible_facts['distribution'] == "CentOS"  

    - name: start and enable apache
      service:
        name: httpd
        enabled: yes
        state: started
      when: ansible_facts['distribution'] == "CentOS"  
    - name: installing PHP packs
      package:
        name: "{{ item }}"
        state: present
      loop:
        - php
        - php-mysql
        - php-fpm
      when: ansible_facts['distribution'] == "CentOS"  
    - name: restart apache
      service:
        name: httpd
        state: restarted
      when: ansible_facts['distribution'] == "CentOS"  

    - name: install apache2 and update ubuntu package definitions
      package:
        name: apache2
        update_cache: yes
        state: present
      when: ansible_facts['distribution'] == "Ubuntu"  
    - name: enable and start apache2
      service:
        name: apache2
        enabled: yes
        state: started
      when: ansible_facts['distribution'] == "Ubuntu"  
    - name: install php
      package:
        name: " {{item}}"
        state: present
      loop:
        - php
        - libapache2-mod-php
        - php-mysql
        - php-mysql
      when: ansible_facts['distribution'] == "Ubuntu"  
    - name: restart apache
      service:
        name: apache2
        state: restarted
      when: ansible_facts['distribution'] == "Ubuntu"
